port:
    8080

addr:
    0.0.0.0

templates:
    'templates/*'

indexes:
    - index.html

redirects:
    - regex: '^(.*)/coolcar.html$'
      url:   '$1/galaxie.html'
      code:  302

    - regex: '^/a2-test/(.*)/1\.[234]/(.*)'
      url:   '/a2-test/$1/1.1/$2'
      code:  302

    - regex: '^(.*)/mercury/(.*)$'
      url:   '$1/ford/$2'
      code:  301
